- type: loadout
  id: LoadoutBoSMidwestUnknown
  category: Outer
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
  items:
    - N14ClothingOuterPowerArmorMidwest

- type: loadout
  id: LoadoutBoSMidwestUnknown2
  category: Outer
  cost: 10
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
  items:
    - N14ClothingOuterPowerArmorMidwestCommander

- type: loadout
  id: LoadoutClothingOuterBOSInquisitorBlackCoat
  category: Outer
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 216000 # 60 hours
  items:
    - N14ClothingOuterBOSInquisitorBlackCoat

- type: loadout
  id: LoadoutClothingOuterBOSInquisitorBattleArmor
  category: Outer
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingOuterBOSInquisitorBattleArmor

- type: loadout
  id: LoadoutClothingHeadHatBoSInquisitorHat
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
  items:
    - N14ClothingHeadHatBoSInquisitorHat

- type: loadout
  id: LoadoutClothingHeadHatBoSInquisitorBlackHat
  category: Head
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 216000 # 60 hours
  items:
    - N14ClothingHeadHatBoSInquisitorBlackHat

- type: loadout
  id: LoadoutClothingHeadHatBoSInquisitorBattleHelmet
  category: Head
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingHeadHatBoSInquisitorBattleHelmet

- type: loadout
  id: LoadoutClothingHeadHatBoSInquisitorBattleHelmetHood
  category: Head
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: N14LoadoutHead
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 72000 # 20 hours veterancy unlock
  items:
    - N14ClothingHeadHatBoSInquisitorBattleHelmetHood

- type: loadout
  id: LoadoutMaskBoSMidwestLiner
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSMidKnight
        - BoSMidSquire
        - BoSWashingtonCommander
        - BoSWashingtonPaladin
        - BoSWashingtonKnight
        - BoSWashingtonInitiate
        - BoSWestElderCommander
        - BoSWestPaladin
        - BoSWestKnight
        - BoSWestGunsmith
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodMidwest
          min: 18000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWashington
          min: 18000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWest
          min: 18000
  items:
    - N14ClothingMaskLiner

- type: loadout
  id: LoadoutMaskBoSMidwestLinerBlack
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSMidKnight
        - BoSWashingtonCommander
        - BoSWashingtonPaladin
        - BoSWashingtonKnight
        - BoSWashingtonInitiate
        - BoSWestElderCommander
        - BoSWestPaladin
        - BoSWestKnight
        - BoSWestGunsmith
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodMidwest
          min: 36000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWashington
          min: 36000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWest
          min: 36000
  items:
    - N14ClothingMaskLinerBlack

- type: loadout
  id: LoadoutMaskBoSMidwestLinerElite
  category: Mask
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSWashingtonCommander
        - BoSWashingtonPaladin
        - BoSWestElderCommander
        - BoSWestPaladin
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodMidwest
          min: 36000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWashington
          min: 36000
        - !type:CharacterDepartmentTimeRequirement
          department: BrotherhoodWest
          min: 36000
  items:
    - N14ClothingMaskLinerElite

- type: loadout
  id: LoadoutClothingNeckMWBSShoulderPadFlag
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
  items:
    - N14ClothingNeckMWBSShoulderPadFlag

- type: loadout
  id: LoadoutClothingNeckMWBSKnightShoulderPad
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidKnight
  items:
    - N14ClothingNeckMWBSKnightShoulderPad

- type: loadout
  id: LoadoutClothingNeckMWBSSeniorKnightShoulderPad
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidKnight
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidKnight
      min: 144000
  items:
    - N14ClothingNeckMWBSSeniorKnightShoulderPad

- type: loadout
  id: LoadoutClothingNeckMWBSCommanderKnightShoulderPad
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidKnight
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidKnight
      min: 216000
  items:
    - N14ClothingNeckMWBSKnightCommanderShoulderPad

- type: loadout
  id: LoadoutClothingNeckMWBSPaladintShoulderPad
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
  items:
    - N14ClothingNeckMWBSPaladinShoulderPad

- type: loadout
  id: LoadoutN14ClothingNeckCloakTentBOS
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSMidKnight
        - BoSMidSquire
  items:
    - N14ClothingNeckCloakTentBOS

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPadMasterBlack
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 60000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPadMasterBlack
    
- type: loadout
  id: LoadoutClothingNeckMWBSKnightShoulderPadOrange
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidKnight
  items:
    - N14ClothingNeckMWBSKnightShoulderPadOrange

- type: loadout
  id: LoadoutClothingNeckMWBSInquisitorShoulderPadyoung
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 60
  items:
    - N14ClothingNeckMWBSInquisitorShoulderPadyoung    

- type: loadout
  id: LoadoutClothingNeckMWBSInquisitorShoulderPadslayer
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 3000
  items:
    - N14ClothingNeckMWBSInquisitorShoulderPadslayer    

- type: loadout
  id: LoadoutClothingNeckMWBSInquisitorShoulderPadmajorslayer
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidInquisitor
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidInquisitor
      min: 6000
  items:
    - N14ClothingNeckMWBSInquisitorShoulderPadmajorslayer   

- type: loadout
  id: LoadoutClothingNeckMWBSCommanderShoulderPadorange
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladinCommander
      min: 3000
  items:
    - N14ClothingNeckMWBSCommanderShoulderPadorange   

- type: loadout
  id: LoadoutClothingNeckMWBSCommanderShoulderPadwhite
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladinCommander
      min: 3000
  items:
    - N14ClothingNeckMWBSCommanderShoulderPadwhite   

- type: loadout
  id: LoadoutClothingNeckMWBSCommanderShoulderPadblue
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladinCommander
      min: 3000
  items:
    - N14ClothingNeckMWBSCommanderShoulderPadblue   

- type: loadout
  id: LoadoutClothingNeckMWBSCommanderShoulderPadblack
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladinCommander
      min: 3000
  items:
    - N14ClothingNeckMWBSCommanderShoulderPadblack

- type: loadout
  id: LoadoutClothingNeckMWBSScriberMantle
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidScribe
   
  items:
    - N14ClothingNeckMWBSScriberMantle

- type: loadout
  id: LoadoutClothingNeckMWBSScriberMantleEngineer
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidScribe
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidScribe
      min: 1800
   
  items:
    - N14ClothingNeckMWBSScriberMantleEngineer

- type: loadout
  id: LoadoutClothingNeckMWBSScriberMantleMedic
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidScribe
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidScribe
      min: 1800
   
  items:
    - N14ClothingNeckMWBSScriberMantleMedic

- type: loadout
  id: LoadoutClothingNeckMWBSScriberMantlePolevoy
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidScribe
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidScribe
      min: 1800
   
  items:
    - N14ClothingNeckMWBSScriberMantlePolevoy

- type: loadout
  id: LoadoutClothingNeckMWBSScriberMantleDirector
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidScribe
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidScribe
      min: 6000
   
  items:
    - N14ClothingNeckMWBSScriberMantleDirector

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinChain
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 60
  items:
    - N14ClothingNeckMWBSPaladinChain

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDBlack
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 600
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDBlack

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDOrange
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 600
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDOrange

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDBlue
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 600
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDBlue

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDChainWhite
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 3000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDChainWhite

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDChainOrange
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 3000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDChainOrange

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDChainBlack
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 3000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDChainBlack

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDChainBlue
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 3000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDChainBlue

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDChainGoldWhite
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 6000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDChainGoldWhite

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDChainGoldBlack
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 6000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDChainGoldBlack

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDChainGoldOrange
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 6000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDChainGoldOrange

- type: loadout
  id: LoadoutClothingNeckMWBSPaladinShoulderPaDChainGoldBlue
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladin
    - !type:CharacterPlaytimeRequirement
      tracker: BoSMidPaladin
      min: 6000
  items:
    - N14ClothingNeckMWBSPaladinShoulderPaDChainGoldBlue

- type: loadout
  id: LoadoutClothingNeckMWBSShoulderPadPatriot
  category: Neck
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - BoSMidPaladinCommander
        - BoSMidPaladin
        - BoSMidKnight
        - BoSMidScribe
        - BoSMidInquisitor
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodMidwest
      min: 60000
  items:
    - N14ClothingNeckMWBSShoulderPadPatriot