- type: job
  id: BoSWashingtonKnight
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-washington-knight
  description: job-description-bos-washington-knight
  playTimeTracker: BoSWashingtonKnight
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWashington
      min: 21600 # Forge-Change (6 hours)
  startingGear: BoSWashingtonKnightGear
  alwaysUseSpawner: true
  icon: "JobIconbosWKnight"
  supervisors: job-supervisors-bos-wash-knight
  access:
  - WashingtonInitiate
  - WashingtonKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - BrotherhoodWashington

- type: startingGear
  id: BoSWashingtonKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitWBoSClassic # Forge-Change
    back: N14ClothingBackpackMilitary # Forge-Change
    shoes: N14ClothingBootsCombat
    gloves: N14ClothingHandsGlovesCombat
    eyes: N14ClothingEyesGlassesWBoS # Forge-Add
    mask: ClothingMaskNeckGaiter # Forge-Add
    head: N14ClothingHeadHatWBoSBattleHelmet # Forge-Change
    outerClothing: N14ClothingOuterWBoSKnightBattleArmor # Forge-Change
    id: N14IDBrotherhoodWashingtonHolotagKnight
    belt: ClothingBeltBoSWebbing
    pocket1: BoSWashingtonKnightSet
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWashingtonKnight
