- type: job
  id: BoSWashingtonScribe
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-washington-scribe
  description: job-description-bos-washington-scribe
  playTimeTracker: BoSWashingtonScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWashington
      min: 28800 # Forge-Change (8 hours)
  startingGear: BoSWashingtonScribeGear
  alwaysUseSpawner: true
  icon: "JobIconbosWScriptor"
  supervisors: job-name-bos-wash
  access:
  - WashingtonInitiate
  - WashingtonScribe
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - BrotherhoodWashington
      - type: CPRTraining

- type: startingGear
  id: BoSWashingtonScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitWBoSClassic # Forge-Change
    back: N14ClothingBackpackMilitary # Forge-Change
    gloves: N14ClothingHandsGlovesCombat # Forge-Add
    shoes: N14ClothingBootsCombatFilled # Forge-Change
    id: N14IDBrotherhoodWashingtonHolotagScribe
    outerClothing: N14ClothingOuterWBoSScripterCoat # Forge-Add
    eyes: N14ClothingEyesGlassesWBoSEyepiece # Forge-Add
    head: N14ClothingHeadHatWBoSBeret # Forge-Add
    ears: N14ClothingHeadsetBOSWashingtonLightScribe
    pocket1: BoSWashingtonScribeKits
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWashingtonScribe
