using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Warfront;
using Content.Shared._Forge.Warfront.CapturePoint;
using Content.Shared._Forge.Warfront.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Forge.Warfront.CapturePoint.UI;

[GenerateTypedNameReferences]
public sealed partial class CapturePointWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPlayerManager _player = default!;

    private static readonly SpriteSpecifier.Rsi NcrFlag =
        new(new ResPath("/Textures/_Nuclear14/Structures/Decoration/flags.rsi"), "ncrflag");

    private static readonly SpriteSpecifier.Rsi LegionFlag =
        new(new ResPath("/Textures/_Nuclear14/Structures/Decoration/flags.rsi"), "legionflag");

    private CapturePointBoundUserInterfaceState _state = new();

    public event Action? CaptureStart;

    public CapturePointWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CaptureButton.OnPressed += _ => CaptureStart?.Invoke();
    }

    public void UpdateState(CapturePointBoundUserInterfaceState state)
    {
        _state = state;

        if (!string.IsNullOrEmpty(state.Title))
            Title = Loc.GetString(state.Title);

        var displayedFaction = state.CaptureInProgress ? state.Attacker : state.Owner;
        var spriteSys = _entity.EntitySysManager.GetEntitySystem<SpriteSystem>();
        OwnerFlagTexture.Texture = displayedFaction switch
        {
            WarfrontFaction.NCR => spriteSys.Frame0(NcrFlag),
            WarfrontFaction.Legion => spriteSys.Frame0(LegionFlag),
            _ => null,
        };
    }

    private WarfrontFaction? GetLocalFaction()
    {
        if (_player.LocalEntity is not { } local)
            return null;

        return _entity.TryGetComponent<WarfrontFactionComponent>(local, out var comp)
            ? comp.Faction
            : null;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var now = _timing.CurTime;

        if (_state.CaptureInProgress)
        {
            var remaining = (_state.CaptureEndTime - now).TotalSeconds;
            CooldownBar.Value = _state.CaptureDurationSeconds > 0
                ? (float) Math.Clamp(1.0 - remaining / _state.CaptureDurationSeconds, 0, 1)
                : 1f;
        }
        else if (now < _state.CooldownEndTime)
        {
            var remaining = (_state.CooldownEndTime - now).TotalSeconds;
            CooldownBar.Value = _state.CooldownSeconds > 0
                ? (float) Math.Clamp(1.0 - remaining / _state.CooldownSeconds, 0, 1)
                : 1f;
        }
        else
        {
            CooldownBar.Value = 0f;
        }

        PayoutTimerValueLabel.Text = _state.Owner != null
            ? FormatCountdown(_state.NextPayoutTime - now)
            : Loc.GetString("capture-point-timer-none");

        var localFaction = GetLocalFaction();
        CaptureButton.Disabled = localFaction == null
            || _state.CaptureInProgress
            || now < _state.CooldownEndTime
            || _state.Owner == localFaction;
    }

    private static string FormatCountdown(TimeSpan remaining)
    {
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        return $"{remaining.Minutes:00}:{remaining.Seconds:00}";
    }
}
