- type: startingGear
  id: RaiderPowerArmorBossNPC
  equipment:
    jumpsuit: ClothingUniformMNKUnderGarment
    outerClothing: N14ClothingOuterPowerArmorRaiderNPC 
    head: N14ClothingHeadHelmetPowerArmorRaiderNPC
    shoes: N14ClothingBootsCombatMK2
    back: N14ClothingPowerSystemsBackRaiderNPC
    pocket1: N14CurrencyCap500 

- type: startingGear
  id: MercenaryHeavySniperNPC
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMilUniform
    outerClothing: N14ClothingOuterVestChinese
    head: ClothingHeadHatBeretMerc
    shoes: N14ClothingBootsCombat
    mask: N14ClothingMaskPatriotMask
    eyes: ClothingEyesGlassesSunglasses
    neck: N14ClothingNeckCloakGhillie
    gloves: N14ClothingHandsGlovesCloth
    pocket1: N14MercStash

- type: startingGear
  id: RaiderButcherNPC
  equipment:
    jumpsuit: ClothingUniformMNKUnderGarment
    outerClothing: ClothingOuterApronChemist
    shoes: ClothingShoesBootsFishing
    mask: N14ClothingMaskPlate
    gloves: ClothingHandsGlovesChemist
    pocket1: N14MercStash
  inhand:
  - N14ripper

- type: startingGear
  id: PsychoRaiderGear1
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    outerClothing: N14ClothingOuterRaiderBlastmaster
    shoes: N14ClothingShoesTribal
    head: N14ClothingTribalMuffaloskull
    pocket1: N14RaiderStash
  inhand:
  - N14ButchersCleaver

- type: startingGear
  id: PsychoRaiderGear2
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    outerClothing: N14ClothingOuterPainspike
    shoes: N14ClothingBootsBlack
    mask: N14ClothingMaskHockey
    pocket1: N14RaiderStash
  inhand:
  - N14ScrapMachete

- type: startingGear
  id: PsychoRaiderGear3
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    outerClothing: N14ClothingOuterLightMetalArmor
    shoes: N14ClothingBootsLeather
    mask: N14ClothingMaskGrill
    pocket1: N14RaiderStash
  inhand:
  - N14BrokenPipe

- type: startingGear
  id: FernMercLieutenantGear1
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCombat
    shoes: N14ClothingBootsCombat
    gloves: N14ClothingHandsGlovesCombat
    head: N14ClothingHeadHatArmyBeretSpecial
    neck: ClothingNeckHeadphones
    mask: N14ClothingMaskPatriotMask
    eyes: N14ClothingEyesSunGlasses
    outerClothing: N14ClothingOuterCoatCombatDuster
    belt: ClothingBeltMilitary
    pocket1: N14MercStash

#Племенные рейдеры.

- type: startingGear
  id: TribalWarriorSwordGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuittribalpantsnecklace
    outerClothing: N14ClothingOuterTribalCoat
    head: ClothingHeadHelmetBone
    shoes: N14ClothingShoesTribal
    back: N14TribalStash
  inhand:
  - N14TribalSword

- type: startingGear
  id: TribalWarriorHunterGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitdrylanderTribal
    outerClothing: N14ClothingOuterBandito
    head: N14ClothingTribalShemagh
    shoes: N14ClothingBootsLeather
    gloves: N14ClothingHandsGlovesTribal
    back: N14TribalStash

- type: startingGear
  id: TribalWarriorElderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitdrylanderTribal
    outerClothing: N14ClothingOuterElderwintercoat
    head: N14ClothingHeadHatEldersDamagedSkullHelm
    shoes: N14ClothingShoesKaligi
    gloves: N14ClothingHandsGlovesTribal
    back: N14TribalStash

- type: startingGear
  id: TribalWarriorBerserkGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuittribalpantsm
    outerClothing: N14ClothingOuterheadtaker
    head: N14ClothingHeadTakerwraps
    shoes: N14ClothingShoesKaligi
    gloves: N14ClothingHandsGlovesTribal
    back: N14TribalStash

#MARK: Китайцы

- type: startingGear
  id: ChineseFighterGear1
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitFudd
    outerClothing: N14ClothingOuterRaiderBlastmaster
    shoes: N14ClothingShoesJamrock
    mask: N14ClothingMaskGreenMask
    gloves: N14ClothingHandsGlovesTribal
    pocket1: N14MercStash 
  inhand:
  - N14PoliceBaton

- type: startingGear
  id: ChineseFighterGear2
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitPreWarRelaxed
    outerClothing: N14ClothingOuterCoatWinterArmored
    head: ClothingHeadHatUshanka
    shoes: ClothingShoesBootsMantis
    gloves: N14ClothingHandsGlovesFur
    pocket1: N14MercStash 
  inhand:
  - N14BrokenPipe
    
- type: startingGear
  id: ChineseFighterGear3
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBrahminFarmer
    outerClothing: N14ClothingOuterRaiderBadlands
    head: N14ClothingHeadHatVancouver
    shoes: N14ClothingBootsLeather
    pocket1: N14MercStash 
  inhand:
  - N14CombatKnife

- type: startingGear
  id: ChineseOfficerGearMob
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitChinese
    outerClothing: N14ClothingOuterCoatSoldierCoat
    head: ClothingHeadHatSyndieMAA
    shoes: N14ClothingBootsCombatMK2
    neck: N14ClothingNeckCloakRangerPoncho
    pocket1: N14MercStash 
  inhand:
  - N14ChineseSword

- type: startingGear
  id: ChinesePistolGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMilUniform
    outerClothing: N14ClothingOuterCombatRaider
    head: N14ClothingHeadHatChinese
    shoes: N14ClothingShoesRaider
    pocket1: N14MercStash 

- type: startingGear
  id: ChineseRifleSKSGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMilUniform
    outerClothing: N14ClothingOuterCombatRusted
    head: N14ClothingHeadHatChinese
    eyes: N14ClothingEyesGlassesWelding
    shoes: N14ClothingBootsLeather
    pocket1: N14MercStash 

- type: startingGear
  id: ChineseShotgunGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitChinese
    outerClothing: N14ClothingOuterRaiderCombat1
    head: N14ClothingHeadHatChineseHelmet
    eyes: N14ClothingEyesGlassesWelding
    shoes: N14ClothingBootsCombat
    pocket1: N14MercStash 

- type: startingGear
  id: ChineseAssaultRifleGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitChinese
    outerClothing: N14ClothingOuterVestChinese
    head: N14ClothingHeadHatChineseHelmet
    shoes: N14ClothingBootsLeather
    pocket1: N14MercStash 

- type: startingGear
  id: ChineseSniperRifleGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitChinese
    outerClothing: N14ClothingOuterVestChinese
    head: N14ClothingHeadHatChineseHelmet
    eyes: N14ClothingEyesGlassesWelding
    shoes: N14ClothingBootsCombat
    neck: N14ClothingNeckCloakGhillie
    pocket1: N14MercStash 

- type: startingGear
  id: ChineseSMGAdvancedGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitChinese
    outerClothing: N14ClothingOuterCombatArmorChinese
    head: N14ClothingHeadHatChineseHelmetMk2
    eyes: N14ClothingEyesGlassesWelding
    hands: N14ClothingHandsGlovesBlackLeather
    shoes: N14ClothingBootsCombatMK2
    mask: N14ClothingMaskBlackBalaclava
    pocket1: N14MercStash 

- type: startingGear
  id: ChinesePowerArmorGear
  equipment:
    jumpsuit: ClothingUniformMNKUnderGarment
    outerClothing: N14ClothingOuterPowerArmorT51ChinaRaiderNPC
    head: N14ClothingHeadHelmetPowerArmorT51ChinaRaiderNPC
    shoes: N14ClothingBootsCombatMK2
    back: N14ClothingPowerSystemsBackRaiderNPC
    pocket1: N14CurrencyCap500 