using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Forge.Silicons.LawCard;
using Content.Shared.FixedPoint;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Forge.Silicons.LawCard;

[GenerateTypedNameReferences]
public sealed partial class LawCardWindow : FancyWindow
{
    private List<SiliconLaw> _laws = new();

    public LawCardWindow()
    {
        RobustXamlLoader.Load(this);

        NewLawButton.OnPressed += _ => AddNewLaw();
    }

    public void SetLaws(List<SiliconLaw> laws)
    {
        _laws = laws;
        Refresh();
    }

    private void AddNewLaw()
    {
        if (_laws.Count >= LawCardComponent.MaxLaws)
            return;

        _laws.Add(new SiliconLaw { Order = FixedPoint2.New(_laws.Count + 1) });
        Refresh();
    }

    private void DeleteLaw(SiliconLaw law)
    {
        _laws.Remove(law);
        Refresh();
    }

    private void Refresh()
    {
        NewLawButton.Disabled = _laws.Count >= LawCardComponent.MaxLaws;
        LawContainer.RemoveAllChildren();
        var position = 1;
        foreach (var law in _laws.OrderBy(l => l.Order))
        {
            var entry = new LawCardEntry();
            entry.SetLaw(law, position);
            entry.OnDelete += DeleteLaw;
            entry.OnLawChanged += UpdateSaveButton;
            LawContainer.AddChild(entry);
            position++;
        }

        UpdateSaveButton();
    }

    private void UpdateSaveButton()
    {
        Save.Disabled = _laws.Any(law => law.LawString.Length > LawCardComponent.MaxLawLength);
    }

    public List<SiliconLaw> GetLaws()
    {
        var ordered = _laws.OrderBy(l => l.Order).ToList();
        for (var i = 0; i < ordered.Count; i++)
            ordered[i].Order = FixedPoint2.New(i + 1);
        return ordered;
    }

    public void SetOverwriteAccess(bool value) => OverwriteAccessCheck.Pressed = value;

    public bool GetOverwriteAccess() => OverwriteAccessCheck.Pressed;
}
