using System;
using Content.Shared._Forge.Silicons.LawCard;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Forge.Silicons.LawCard;

[GenerateTypedNameReferences]
public sealed partial class LawCardEntry : PanelContainer
{
    private SiliconLaw? _law;

    // Guards against the OnTextChanged handler firing while SetLaw populates the field
    // programmatically, which would overwrite the law's (possibly localization-key) string.
    private bool _populating;

    public event Action<SiliconLaw>? OnDelete;
    public event Action? OnLawChanged;

    public LawCardEntry()
    {
        RobustXamlLoader.Load(this);

        LawContent.OnTextChanged += _ =>
        {
            if (_populating)
                return;

            _law!.LawString = Rope.Collapse(LawContent.TextRope).Trim();
            UpdateValidity();
            OnLawChanged?.Invoke();
        };
        LawContent.Placeholder = new Rope.Leaf(Loc.GetString("law-card-ui-placeholder"));
        Delete.OnPressed += _ => OnDelete?.Invoke(_law!);
    }

    public void SetLaw(SiliconLaw law, int position)
    {
        _law = law;
        _populating = true;
        LawContent.TextRope = new Rope.Leaf(Loc.GetString(law.LawString));
        _populating = false;
        PositionText.Text = Loc.GetString("laws-ui-law-header", ("id", position));
        UpdateValidity();
    }

    private void UpdateValidity()
    {
        var tooLong = _law!.LawString.Length > LawCardComponent.MaxLawLength;
        LawContent.ToolTip = tooLong
            ? Loc.GetString("news-writer-text-length-exceeded")
            : null;
    }
}
